export const Users = [
  {
    id:1,
    profilePicture: "assets/person/1.jpeg",
    username: "Safak Kocaoglu",
  },
  {
    id:2,
    profilePicture: "assets/person/2.jpeg",
    username: "Janell Shrum",
  },
  {
    id:3,
    profilePicture: "assets/person/3.jpeg",
    username: "Alice Italiano",
  },
  {
    id:4,
    profilePicture: "assets/person/4.jpeg",
    username: "Dora Hawks",
  },
  {
    id:5,
    profilePicture: "assets/person/5.jpeg",
    username: "Katelyn Brockmann",
  },
  {
    id:6,
    profilePicture: "assets/person/9.jpeg",
    username: "Josey Williams",
  },
  {
    id:7,
    profilePicture: "assets/person/7.jpeg",
    username: "Aryan Goel",
  },
  {
    id:8,
    profilePicture: "assets/person/8.jpeg",
    username: "Kristen Thomas",
  },
  {
    id:9,
    profilePicture: "assets/person/6.jpeg",
    username: "Eva Cudmor",
  },
  {
    id:10,
    profilePicture: "assets/person/10.jpeg",
    username: "Taylor Swift",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "New hair",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 102,
    comment: 19,
  },
  {
    id: 2,
    photo: "assets/post/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 20067899,
    comment: 9100,
  },
  {
    id: 3,
    desc: "In a Match !!",
    photo: "assets/post/11.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 194,
    comment: 45,
  },
  {
    id: 4,
    photo: "assets/post/4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7000000,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/post/5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 2300000,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/post/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/post/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/post/8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 1500,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/post/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 1100000,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/post/10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104000,
    comment: 12,
  },
];
